### ISSUE TITLE
Roadmap for v0.3.0 release

### ISSUE THREAD

**Issue by junyuan-chen** [junyuan-chen/ReadStatTables.jl#20]
The upcoming v0.2.3 release is very likely to be the last one in the v0.2.x series. Development will target toward the v0.3.0 release once v0.2.3 is out. The goal is to get close to a full coverage of the [ReadStat API](https://github.com/WizardMac/ReadStat/blob/master/src/readstat.h) for complete functionality while maintaining the performance advantage over the related packages.

Here is a list of changes that have been planned for v0.3.0:

- [ ] Use `MappedArray` to lazily convert variables in date/time format back and forth between format-specific numerical values and Julia `Date`/`DateTime`.
- [ ] Support user-specified missing values (`.a`, ..., `.z` and value ranges) while maintaining the ease of getting back to `missing` (possibly with `StructArray` and `MappedArray`).
- [ ] Support `READSTAT_TYPE_STRING_REF` for very long strings in Stata.
- [ ] Add an `allowcopy` option to `writestat` for converting the user-provided table to `ReadStatTable{ReadStatColumn}` before row iteration. This could make writing data files faster.
- [ ] Support reading/writing data by chunk.
- [ ] Reproduce the sample data used for testing, ideally with scripts executed on Stata/SAS/SPSS.
- [ ] Require Julia v1.6 and ReadStat_jll.jl v1.1.8. Check compatibility of dependencies.

**Comment by andreasnoack** [comment]
The current version is 0.3.2 so this one needs an update or maybe it can be closed

**Comment by junyuan-chen** [comment]
@andreasnoack Thanks! I should modify the title to avoid confusion, as this issue now becomes a reminder for things that may be considered for future v0.3.x.
